name: Branch Naming Policy

on:
  create:
  delete:
  pull_request:
    branches: [ main, master ]

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Branch Naming Policy Action
        uses: nicklegan/github-repo-branch-naming-policy-action@v1.1.0
        if: github.ref_type == 'branch' || github.ref_type == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Updates:
          # 1. \d+- allows "123-somename" (GitHub default) and "1-WORDS"
          # 2. (feature|fix|...)\/ allows "feature/somename", "fix/1-WORDS"
          # 3. [a-zA-Z0-9\-_]+ allows uppercase in names (e.g. WORDS)
          regex: '^((feature|bugfix|hotfix|test|fix|docs)\/|\d+-)[a-zA-Z0-9\-_]+$'